#!/usr/bin/with-contenv bash

echo "[LetsOrg] Starting..."
echo "[LetsOrg] Cleaning Reverse Proxy modules"
rm -rf /config/nginx/rproxy-enabled
rm -rf /config/nginx/rproxy-available
mkdir -p /config/nginx/rproxy-enabled
mkdir -p /config/nginx/rproxy-available
chown -R abc:abc /config/nginx/rproxy-*

# get defaults into config
cp /defaults/proxymodules/*.conf /config/nginx/rproxy-available/

# enable auth
sed -i 's!%%%URL%%%!'$URL'!' /config/nginx/rproxy-available/auth.conf
ln -s /config/nginx/rproxy-available/auth.conf /config/nginx/rproxy-enabled/auth.conf

echo "[LetsOrg] Checking for Sonarr..."
if [ ! -z "$SONARR_URL" ]; then
    sed -i 's!%%%SONARR_URL%%%!'$SONARR_URL'!' /config/nginx/rproxy-available/sonarr.conf
    ln -s /config/nginx/rproxy-available/sonarr.conf /config/nginx/rproxy-enabled/sonarr.conf
fi

echo "[LetsOrg] Checking for Radarr..."
if [ ! -z "$RADARR_URL" ]; then
    sed -i 's!%%%RADARR_URL%%%!'$RADARR_URL'!' /config/nginx/rproxy-available/radarr.conf
    ln -s /config/nginx/rproxy-available/radarr.conf /config/nginx/rproxy-enabled/radarr.conf
fi

echo "[LetsOrg] Checking for Lidarr..."
if [ ! -z "$LIDARR_URL" ]; then
    sed -i 's!%%%LIDARR_URL%%%!'$LIDARR_URL'!' /config/nginx/rproxy-available/lidarr.conf
    ln -s /config/nginx/rproxy-available/lidarr.conf /config/nginx/rproxy-enabled/
fi

echo "[LetsOrg] Checking for Tautulli..."
if [ ! -z "$TAUTULLI_URL" ]; then
    sed -i 's!%%%TAUTULLI_URL%%%!'$TAUTULLI_URL'!' /config/nginx/rproxy-available/tautulli.conf
    ln -s /config/nginx/rproxy-available/tautulli.conf /config/nginx/rproxy-enabled/tautulli.conf
fi

echo "[LetsOrg] Checking for Ombi..."
if [ ! -z "$OMBI_URL" ]; then
    sed -i 's!%%%OMBI_URL%%%!'$OMBI_URL'!' /config/nginx/rproxy-available/ombi.conf
    ln -s /config/nginx/rproxy-available/ombi.conf /config/nginx/rproxy-enabled/ombi.conf
fi

echo "[LetsOrg] Checking for Guacamole..."
if [ ! -z "$GUACAMOLE_URL" ]; then
    sed -i 's!%%%GUACAMOLE_URL%%%!'$GUACAMOLE_URL'!' /config/nginx/rproxy-available/guacamole.conf
    ln -s /config/nginx/rproxy-available/guacamole.conf /config/nginx/rproxy-enabled/guacamole.conf
fi

if [[ -f /config/www/index.html ]]; then
    echo "[LetsOrg] Cleaning Current WebRoot..."
    rm -rf /config/www
    echo "[LetsOrg] Cloning Organizr..."
    git clone -b v2-develop https://github.com/causefx/Organizr /config/www/
    echo "[LetsOrg] Checking permissions..."
    chown -R abc:abc /config/www
else
    echo "[LetsOrg] Checking for Organizr updates..."
    cd /config/www
    git pull
    echo "[LetsOrg] Checking permissions..."
    chown -R abc:abc /config/www
fi

echo "[LetsOrg] Finished"
